# Conexi贸n con la base de datos principal
database:
  host: localhost
  user: root
  pass: 
  name: emergente
  port: 1521
  protocol: TCP
  motor: mysql
  
# Configuraci贸n de servidor SMTP
phpmailer:
  host: 
  user: 
  pass: 
  port: 465

# Configuraci贸n de sesiones
sessions:
  life_time: 3600 

# Variables del framework
framework:
  debug: false
  version: 2.0.0

# Configuraci贸n del sitio
site:
  name: Emergente
  author: DevSystemVzla
  author_email: devsystemvzla@gmail.com
  url: http://localhost/emergente/
  timezone: America/Caracas
  router:
    path: localhost/emergente/
    protocol: http
